### ISSUE TITLE
Do we need to enter or just put :gdrebuildcache in the alfred entry?

### ISSUE THREAD

**Issue by chang-you** [alfredapp/google-drive-workflow#6] opened 2021-12-10 03:19 UTC
### Workflow version

2021.11

### Alfred version

4.6.1[1274]

### macOS version

12.0.1

### Debugger output

```alfred_debugger
[19:18:07.651] Logging Started...
[19:18:32.928] Google Drive[Keyword] Processing complete
[19:18:32.932] Google Drive[Keyword] Passing output '' to Run Script
[19:18:33.088] ERROR: Google Drive[Run Script] Ignoring bcrypt-3.1.16 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.16
Ignoring bigdecimal-2.0.0 because its extensions are not built. Try: gem pristine bigdecimal --version 2.0.0
Ignoring bindex-0.8.1 because its extensions are not built. Try: gem pristine bindex --version 0.8.1
Ignoring bootsnap-1.7.5 because its extensions are not built. Try: gem pristine bootsnap --version 1.7.5
Ignoring byebug-11.1.3 because its extensions are not built. Try: gem pristine byebug --version 11.1.3
Ignoring date-3.0.0 because its extensions are not built. Try: gem pristine date --version 3.0.0
Ignoring dbm-1.1.0 because its extensions are not built. Try: gem pristine dbm --version 1.1.0
Ignoring etc-1.1.0 because its extensions are not built. Try: gem pristine etc --version 1.1.0
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.15.1 because its extensions are not built. Try: gem pristine ffi --version 1.15.1
Ignoring ffi-1.15.0 because its extensions are not built. Try: gem pristine ffi --version 1.15.0
Ignoring ffi-1.13.0 because its extensions are not built. Try: gem pristine ffi --version 1.13.0
Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring io-console-0.5.6 because its extensions are not built. Try: gem pristine io-console --version 0.5.6
Ignoring jaro_winkler-1.5.4 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.4
Ignoring json-2.5.1 because its extensions are not built. Try: gem pristine json --version 2.5.1
Ignoring json-2.3.0 because its extensions are not built. Try: gem pristine json --version 2.3.0
Ignoring libxml-ruby-3.2.0 because its extensions are not built. Try: gem pristine libxml-ruby --version 3.2.0
Ignoring msgpack-1.4.2 because its extensions are not built. Try: gem pristine msgpack --version 1.4.2
Ignoring nio4r-2.5.7 because its extensions are not built. Try: gem pristine nio4r --version 2.5.7
Ignoring pg-1.2.3 because its extensions are not built. Try: gem pristine pg --version 1.2.3
Ignoring puma-5.3.1 because its extensions are not built. Try: gem pristine puma --version 5.3.1
Ignoring puma-3.12.6 because its extensions are not built. Try: gem pristine puma --version 3.12.6
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring sassc-2.4.0 because its extensions are not built. Try: gem pristine sassc --version 2.4.0
Ignoring sqlite3-1.4.2 because its extensions are not built. Try: gem pristine sqlite3 --version 1.4.2
Ignoring unf_ext-0.0.7.7 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.7
Ignoring websocket-driver-0.7.3 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.3
Ignoring websocket-driver-0.6.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.5
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/date-3.0.0/lib/date_core.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/date-3.0.0/lib/date_core.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/date_core.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/date-3.0.0/lib/date_core.bundle (LoadError)
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/date-3.0.0/lib/date.rb:4:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/time.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13/lib/sqlite3/translator.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:5:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:9:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:160:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:149:in `require'
	from /Users/yoci642/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E96BEA1B-DBD3-4E6B-BB6F-8543B0CECAB2/rebuild_cache:6:in `<main>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- sqlite3 (LoadError)
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Users/yoci642/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E96BEA1B-DBD3-4E6B-BB6F-8543B0CECAB2/rebuild_cache:6:in `<main>'
[19:18:33.105] Google Drive[Run Script] Processing complete
[19:18:33.105] Google Drive[Run Script] Passing output '' to Run Script
[19:18:33.105] Google Drive[Run Script] Passing output '' to Conditional
[19:18:33.106] Google Drive[Conditional] Processing complete
[19:18:33.106] Google Drive[Conditional] Passing output '' to Conditional
[19:18:33.106] Google Drive[Conditional] Processing complete
[19:18:33.107] Google Drive[Conditional] Passing output '' to Post Notification
```

### More details

Run `:gdrebuildcache` but fail

**Comment by vitorgalvao** [comment] 2021-12-10 15:18
That shows a problem in your local installation of Ruby. It is unlikely you made it happen, but the error is neither caused nor can it be fixed by the Workflow.

> (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

Meaning you are on Apple Silicon but your system Ruby is trying to run as if it were an Intel machine.

The first thing I’d do is reboot. I doubt it will fix this issue, but I’ve seen others go away.

If the problem persists, it means it’s a deeper issue in your macOS installation. [Back in January someone wrote a post](https://betterprogramming.pub/ruby-on-apple-silicon-m1-macs-fb159849b2f5) detailing this issue. Unfortunately the cause and fix aren’t clear and this isn’t a pervasive issue so there aren’t many resources on it. Were I able to reproduce I could try to give you more details, but since I can’t it limits my ability to investigate.

But this will affect every Ruby script on your system and is ultimately *something* broken in your macOS installation. That needs to be fixed at a deeper level.

**Closed as completed by vitorgalvao** 2021-12-10 15:18 UTC

**Comment by chang-you** [comment] 2021-12-12 05:45
> 

Thank you, so again, do we need to hit enter when input `:gdrebuildcache` ? Or just wait for it?

**Comment by chang-you** [comment] 2021-12-12 05:45
```
[21:44:08.274] Google Drive Search[Script Filter] Queuing argument '(null)'
[21:44:08.419] Google Drive Search[Script Filter] Script with argv '(null)' finished
[21:44:08.420] ERROR: Google Drive Search[Script Filter] Code 1: 2021-12-11 21:44:08.415 osascript[6116:42271] CFURLGetFSRef was passed a URL which has no scheme (the URL will not work with other CFURL routines)
/Users/yoci642/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/E59D8180-1B9E-4441-9547-0F24A8E53E77:8:42: 2021-12-11 21:44:08.416 osascript[6116:42271] CFURLCopyResourcePropertyForKey failed because it was passed a URL which has no scheme
execution error: Can’t make file ":GoogleDrive.json" into type file. (-1700)
```

And here's the new bug report after I reboot my MacBook, thank you!

**Comment by vitorgalvao** [comment] 2021-12-12 12:24
> Thank you, so again, do we need to hit enter

Yes. But you shouldn’t be calling that anyway, you should be using `:gdlaunchd`. The instructions explain all of this.

But that’s irrelevant until you fix the problem with your installation.

> And here's the new bug report after I reboot my MacBook, thank you!

That has nothing to do with this Workflow; you’re doing something else.
